name: CI Pipeline

on:
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
    ci-job:
        runs-on: ubuntu-latest
        environment: env
        env:
            IMAGE_NAME: kareemelgiushy/java:v${{github.run_number}}
        steps:
            - uses: actions/checkout@v4
            - name: "kareem"
              run: |
                echo "heelo"
            - name: Setup Java JDK
              uses: actions/setup-java@v4
              with:
                  java-version: "11"
                  distribution: "adopt"
            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: java-app-jar    
                path: target/*.jar

            - name: "build with maven"
              run: mvn clean install
            - name: "docker build"
              run: docker build -t $IMAGE_NAME .
            - name: "docker login"
              run: docker login -u ${{secrets.DOCKERUSERNAME}} -p ${{secrets.DOCKERPASS}}
            - name: "docker push image"
              run: docker push $IMAGE_NAME
